### ISSUE TITLE
streamlit run app.py运行后出错 FileNotFoundError: [Errno 2] No such file or directory: './repos'

### ISSUE THREAD

**Issue by nicekate** [jw782cn/RepoChat-200k#7]
streamlit run app.py运行后出错：

FileNotFoundError: [Errno 2] No such file or directory: './repos'

看到演示，项目很不错

**Comment by jw782cn** [comment]
这个上次commit fix了，你看拉最新的可以解决吗？实在不行就自己创建一个repos的目录？

**Comment by jw782cn** [comment]
啊哈，我push到另一个branch上了，难怪，已经修复了。
